### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by lawloretienne** [galens/playback-gpx#2]
There is a missing module.  How do you resolve this?

Traceback (most recent call last):
  File "playback-gpx.py", line 7, in <module>
    import gpxpy
ImportError: No module named gpxpy

**Comment by galens** [comment]
Hi,

Gpxpy is a python gpx file parser which can be downloaded from here:
https://pypi.python.org/packages/source/g/gpxpy/gpxpy-0.9.8.tar.gz

Either install it or ensure the file sits in the same directory and this script will work.

**Comment by lawloretienne** [comment]
Okay so i tried the updated 0.9.8 version and now i get this error

~$ python playback-gpx.py -i 1 -r "-r 192.168.56.101" ~/Downloads/0312172032-24090.gpx
INFO:root:processing /Users/etiennelawlor/Downloads/0312172032-24090.gpx
GPXTrack(description=u'Length: 0.437 km (0.272 mi)', number=0, segments=[GPXTrackSegment(points=[...])])
INFO:root:Point at (37.7771037,-122.3967907,0.0)
Traceback (most recent call last):
  File "playback-gpx.py", line 96, in <module>
    process_file(path, options)
  File "playback-gpx.py", line 37, in process_file
    set_point(point, options)
  File "playback-gpx.py", line 57, in set_point
    logging.debug(check_output([options.command, "-c", "gps setlatitude " + str(point.latitude), options.ipaddress]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by moopat** [comment]
@lawloretienne I am having the same problem. Did you find out how to solve this problem?

**Comment by moopat** [comment]
The error means that the genyshell cannot be found because most likely genymotion was not installed in its default location. I created a pull request that will show an error message in that case and also advise the user to use the `-g` flag to set the current genyshell path: #5.
