### ISSUE TITLE
Returned non-zero exit status

### ISSUE THREAD

**Issue by junalmeida** [galens/playback-gpx#3]
```
>python playback-gpx.py -i 1 -r "-r 192.168.56.101" "docs/South On Topanga(1).gpx"
INFO:root:processing docs/South On Topanga(1).gpx
GPXTrack(name=u'South On Topanga', description=u'Driving south on Topanga', segments=[GPXTrackSegment(points=[...])])
INFO:root:Point at (34.259003,-118.606278,256.8)
Qt: Untested Windows version 10.0 detected!
Traceback (most recent call last):
  File "playback-gpx.py", line 96, in <module>
    process_file(path, options)
  File "playback-gpx.py", line 37, in process_file
    set_point(point, options)
  File "playback-gpx.py", line 57, in set_point
    logging.debug(check_output([options.command, "-c", "gps setlatitude " + str(point.latitude), options.ipaddress]))
  File "C:\Python27\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Genymobile\\Genymotion\\genyshell.exe', '-c', 'gps setlatitude 34.259003', '-r 192.168.56.101']' returned non-zero exit status -1
```

**Comment by riskids** [comment]
same problem. Did you find out to solve this problem?
